import { execFile, spawn } from 'node:child_process';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';
import { daemonHome } from '../paths.js';
import type { DaemonExec, Host, HostStatus } from './host.js';

const exec = promisify(execFile);

export const WINDOWS_RUN_KEY = 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run';
export const WINDOWS_RUN_VALUE = 'KmanDaemon';

/**
 * Build the command-line string that actually launches the daemon. Args
 * containing spaces are double-quoted, matching how Windows parses the value.
 */
export function windowsRunCommandValue(daemonExec: DaemonExec): string {
  return [daemonExec.command, ...daemonExec.args]
    .map((a) => (/\s/.test(a) ? `"${a}"` : a))
    .join(' ');
}

/** Path of the generated VBScript shim used to start the daemon without a window. */
export function windowsLauncherPath(): string {
  return join(daemonHome(), 'autostart.vbs');
}

/**
 * VBScript shim contents. Uses the canonical `Set sh = CreateObject(...)` /
 * `sh.Run` form (the one-liner `CreateObject(...).Run "x", 0, False` is invalid
 * VBScript and fails to parse). Window-style `0` launches the daemon completely
 * hidden — no console window flashes at login. Embedded double quotes are
 * doubled per VBScript string-literal rules.
 */
export function windowsLauncherVbsText(daemonExec: DaemonExec): string {
  const command = windowsRunCommandValue(daemonExec).replace(/"/g, '""');
  return (
    '\' Auto-generated by kman. Launches the daemon hidden (no console window).\r\n' +
    'Dim sh\r\n' +
    'Set sh = CreateObject("WScript.Shell")\r\n' +
    `sh.Run "${command}", 0, False\r\n`
  );
}

/**
 * Run-key value: invoke the VBScript shim through `wscript.exe` so login starts
 * the daemon silently. `//B` (batch, suppress prompts) and `//Nologo` keep it quiet.
 */
export function windowsAutostartCommandValue(launcherPath: string = windowsLauncherPath()): string {
  return `wscript.exe //B //Nologo "${launcherPath}"`;
}

/** `reg add` argument vector for registering the hidden-launcher autostart. */
export function windowsRegAddArgs(launcherPath: string = windowsLauncherPath()): string[] {
  return [
    'add',
    WINDOWS_RUN_KEY,
    '/v',
    WINDOWS_RUN_VALUE,
    '/t',
    'REG_SZ',
    '/d',
    windowsAutostartCommandValue(launcherPath),
    '/f',
  ];
}

/**
 * Windows host. Autostart is a per-user registry Run-key entry that launches the
 * daemon at login via a hidden VBScript shim, so no admin rights, service
 * wrapper, or console window are needed. Day-to-day start/stop also go through
 * `kman daemon start|stop`, but start() here spawns the daemon detached (and
 * hidden) so `kman daemon install --start` works too.
 */
export class WindowsHost implements Host {
  readonly name = 'windows';
  readonly label = 'Windows (registry autostart)';
  constructor(private readonly daemonExec: DaemonExec) {}

  async install(): Promise<void> {
    const launcher = windowsLauncherPath();
    await mkdir(dirname(launcher), { recursive: true });
    await writeFile(launcher, windowsLauncherVbsText(this.daemonExec), 'utf8');
    await exec('reg', windowsRegAddArgs(launcher));
  }

  async uninstall(): Promise<void> {
    await exec('reg', ['delete', WINDOWS_RUN_KEY, '/v', WINDOWS_RUN_VALUE, '/f']).catch(() => {});
    await rm(windowsLauncherPath(), { force: true }).catch(() => {});
  }

  async start(): Promise<void> {
    const child = spawn(this.daemonExec.command, this.daemonExec.args, {
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
    });
    child.unref();
  }

  async stop(): Promise<void> {
    // The cross-platform path is `kman daemon stop` (graceful IPC shutdown).
    // Nothing host-specific to do here.
  }

  async status(): Promise<HostStatus> {
    try {
      const { stdout } = await exec('reg', ['query', WINDOWS_RUN_KEY, '/v', WINDOWS_RUN_VALUE]);
      return { installed: stdout.includes(WINDOWS_RUN_VALUE), running: false, detail: 'autostart registered' };
    } catch {
      return { installed: false, running: false };
    }
  }
}
